<a href="https://colab.research.google.com/github/vishalmahor886/basic_ML_code/blob/main/iterative_imputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
url = 'https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/main/day40-iterative-imputer/50_Startups.csv'
df = pd.read_csv(url, usecols=['R&D Spend','Administration','Marketing Spend','Profit'])

In [ ]:
df = df/10000

In [ ]:
df.sample(5)

,R&D Spend,Administration,Marketing Spend,Profit
10,10.191308,11.059411,22.916095,14.612195
40,2.875433,11.854605,17.279567,7.823991
1,16.259770,15.137759,44.389853,19.179206
30,6.199448,11.564128,9.113124,9.993759
46,0.131546,11.581621,29.711446,4.949075


In [ ]:
df.isnull().mean()*100

,0
R&D Spend,0.0
Administration,0.0
Marketing Spend,0.0
Profit,0.0


In [ ]:
df = df.iloc[:,0:-1]
df

,R&D Spend,Administration,Marketing Spend
0,16.534920,13.689780,47.178410
1,16.259770,15.137759,44.389853
2,15.344151,10.114555,40.793454
3,14.437241,11.867185,38.319962
4,14.210734,9.139177,36.616842
5,13.187690,9.981471,36.286136
6,13.461546,14.719887,12.771682
7,13.029813,14.553006,32.387668
8,12.054252,14.871895,31.161329
9,12.333488,10.867917,30.498162


In [ ]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

In [ ]:
df.isnull().mean()*100

,0
R&D Spend,2.0
Administration,2.0
Marketing Spend,2.0


In [ ]:
df.sample(5)

,R&D Spend,Administration,Marketing Spend
13,9.199239,13.549507,25.266493
44,2.217774,15.480614,2.833472
16,7.801311,12.159755,26.434606
7,13.029813,14.553006,32.387668
39,3.855851,8.298209,17.499930


In [ ]:
# Step 1 - Impute all missing values with mean of respective col

df0 = pd.DataFrame()

df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [ ]:
# 0th Iteration
df0

,R&D Spend,Administration,Marketing Spend
0,16.534920,13.689780,47.178410
1,7.190782,15.137759,44.389853
2,15.344151,10.114555,40.793454
3,14.437241,12.139919,38.319962
4,14.210734,9.139177,36.616842
5,13.187690,9.981471,36.286136
6,13.461546,14.719887,12.771682
7,13.029813,14.553006,32.387668
8,12.054252,14.871895,31.161329
9,12.333488,10.867917,30.498162


In [ ]:
# Remove the col1 imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
0,16.534920,13.689780,47.178410
1,NaN,15.137759,44.389853
2,15.344151,10.114555,40.793454
3,14.437241,12.139919,38.319962
4,14.210734,9.139177,36.616842
5,13.187690,9.981471,36.286136
6,13.461546,14.719887,12.771682
7,13.029813,14.553006,32.387668
8,12.054252,14.871895,31.161329
9,12.333488,10.867917,30.498162


In [ ]:
# Use first 3 rows to build a model and use the last for prediction

X = df1.iloc[[0,2,3,4],1:3]
X

,Administration,Marketing Spend
0,13.689780,47.178410
2,10.114555,40.793454
3,12.139919,38.319962
4,9.139177,36.616842


In [ ]:
y = df1.iloc[[0,2,3,4],0]
y

,R&D Spend
0,16.534920
2,15.344151
3,14.437241
4,14.210734


In [ ]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([15.68665427])

In [ ]:
df1.iloc[1,0] = 15.68

In [ ]:
df1

,R&D Spend,Administration,Marketing Spend
0,16.534920,13.689780,47.178410
1,15.680000,15.137759,44.389853
2,15.344151,10.114555,40.793454
3,14.437241,12.139919,38.319962
4,14.210734,9.139177,36.616842
5,13.187690,9.981471,36.286136
6,13.461546,14.719887,12.771682
7,13.029813,14.553006,32.387668
8,12.054252,14.871895,31.161329
9,12.333488,10.867917,30.498162


In [ ]:
# Remove the col2 imputed value

df1.iloc[3,1] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
0,16.534920,13.689780,47.178410
1,15.680000,15.137759,44.389853
2,15.344151,10.114555,40.793454
3,14.437241,NaN,38.319962
4,14.210734,9.139177,36.616842
5,13.187690,9.981471,36.286136
6,13.461546,14.719887,12.771682
7,13.029813,14.553006,32.387668
8,12.054252,14.871895,31.161329
9,12.333488,10.867917,30.498162


In [ ]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[[0,1,2,4],[0,2]]
X

,R&D Spend,Marketing Spend
0,16.534920,47.178410
1,15.680000,44.389853
2,15.344151,40.793454
4,14.210734,36.616842


In [ ]:
y = df1.iloc[[0,1,2,4],1]
y

,Administration
0,13.689780
1,15.137759
2,10.114555
4,9.139177


In [ ]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.38062788])

In [ ]:
df1.iloc[3,1] = 11.38

In [ ]:
df1

,R&D Spend,Administration,Marketing Spend
0,16.534920,13.689780,47.178410
1,15.680000,15.137759,44.389853
2,15.344151,10.114555,40.793454
3,14.437241,11.380000,38.319962
4,14.210734,9.139177,36.616842
5,13.187690,9.981471,36.286136
6,13.461546,14.719887,12.771682
7,13.029813,14.553006,32.387668
8,12.054252,14.871895,31.161329
9,12.333488,10.867917,30.498162


In [ ]:
# Remove the col3 imputed value
df1.iloc[4,-1] = np.nan

df1

,R&D Spend,Administration,Marketing Spend
0,16.534920,13.689780,47.178410
1,15.680000,15.137759,44.389853
2,15.344151,10.114555,40.793454
3,14.437241,11.380000,38.319962
4,14.210734,9.139177,NaN
5,13.187690,9.981471,36.286136
6,13.461546,14.719887,12.771682
7,13.029813,14.553006,32.387668
8,12.054252,14.871895,31.161329
9,12.333488,10.867917,30.498162


In [ ]:
# Use last 3 rows to build a model and use the first for prediction
X = df1.iloc[0:4,0:2]
X

,R&D Spend,Administration
0,16.534920,13.689780
1,15.680000,15.137759
2,15.344151,10.114555
3,14.437241,11.380000


In [ ]:
y = df1.iloc[0:4,-1]
y

,Marketing Spend
0,47.178410
1,44.389853
2,40.793454
3,38.319962


In [ ]:
lr = LinearRegression()
lr.fit(X,y)
lr.predict(df1.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36.28976674])

In [ ]:
df1.iloc[4,-1] = 36.28

In [ ]:
df1

,R&D Spend,Administration,Marketing Spend
0,16.534920,13.689780,47.178410
1,15.680000,15.137759,44.389853
2,15.344151,10.114555,40.793454
3,14.437241,11.380000,38.319962
4,14.210734,9.139177,36.280000
5,13.187690,9.981471,36.286136
6,13.461546,14.719887,12.771682
7,13.029813,14.553006,32.387668
8,12.054252,14.871895,31.161329
9,12.333488,10.867917,30.498162


In [ ]:
# Subtract 0th iteration from 1st iteration

df1 - df0

,R&D Spend,Administration,Marketing Spend
0,0.000000,0.000000,0.000000
1,8.489218,0.000000,0.000000
2,0.000000,0.000000,0.000000
3,0.000000,-0.759919,0.000000
4,0.000000,0.000000,-0.336842
5,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.000000
8,0.000000,0.000000,0.000000
9,0.000000,0.000000,0.000000


In [ ]:
df2 = df1.copy()

df2.iloc[1,0] = np.nan

df2

,R&D Spend,Administration,Marketing Spend
0,16.534920,13.689780,47.178410
1,NaN,15.137759,44.389853
2,15.344151,10.114555,40.793454
3,14.437241,11.380000,38.319962
4,14.210734,9.139177,36.280000
5,13.187690,9.981471,36.286136
6,13.461546,14.719887,12.771682
7,13.029813,14.553006,32.387668
8,12.054252,14.871895,31.161329
9,12.333488,10.867917,30.498162


In [ ]:
X = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([15.5197258])

In [ ]:
df2.iloc[1,0] = 15.51

In [ ]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.26664741])

In [ ]:
df2.iloc[3,1] = 11.26

In [ ]:
df2.iloc[4,-1] = np.nan

X = df2.iloc[0:4,0:2]
y = df2.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df2.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36.22942274])

In [ ]:
df2.iloc[4,-1] = 36.22

In [ ]:
df2

,R&D Spend,Administration,Marketing Spend
0,16.534920,13.689780,47.178410
1,15.510000,15.137759,44.389853
2,15.344151,10.114555,40.793454
3,14.437241,11.260000,38.319962
4,14.210734,9.139177,36.220000
5,13.187690,9.981471,36.286136
6,13.461546,14.719887,12.771682
7,13.029813,14.553006,32.387668
8,12.054252,14.871895,31.161329
9,12.333488,10.867917,30.498162


In [ ]:
df2 - df1

,R&D Spend,Administration,Marketing Spend
0,0.00,0.00,0.00
1,-0.17,0.00,0.00
2,0.00,0.00,0.00
3,0.00,-0.12,0.00
4,0.00,0.00,-0.06
5,0.00,0.00,0.00
6,0.00,0.00,0.00
7,0.00,0.00,0.00
8,0.00,0.00,0.00
9,0.00,0.00,0.00


In [ ]:
df3 = df2.copy()

df3.iloc[1,0] = np.nan

df3

,R&D Spend,Administration,Marketing Spend
0,16.534920,13.689780,47.178410
1,NaN,15.137759,44.389853
2,15.344151,10.114555,40.793454
3,14.437241,11.260000,38.319962
4,14.210734,9.139177,36.220000
5,13.187690,9.981471,36.286136
6,13.461546,14.719887,12.771682
7,13.029813,14.553006,32.387668
8,12.054252,14.871895,31.161329
9,12.333488,10.867917,30.498162


In [ ]:
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[1,1:].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([15.48532879])

In [ ]:
df3.iloc[1,0] = 15.48

In [ ]:

df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.24138486])

In [ ]:
df3.iloc[3,1] = 11.24

In [ ]:
df3.iloc[4,-1] = np.nan

X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]

lr = LinearRegression()
lr.fit(X,y)
lr.predict(df3.iloc[4,0:2].values.reshape(1,2))

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([36.22294123])

In [ ]:
df3.iloc[4,-1] = 36.22

In [ ]:
df2.iloc[3,1] = 11.24

In [ ]:
df3

,R&D Spend,Administration,Marketing Spend
0,16.534920,13.689780,47.178410
1,15.480000,15.137759,44.389853
2,15.344151,10.114555,40.793454
3,14.437241,11.240000,38.319962
4,14.210734,9.139177,36.220000
5,13.187690,9.981471,36.286136
6,13.461546,14.719887,12.771682
7,13.029813,14.553006,32.387668
8,12.054252,14.871895,31.161329
9,12.333488,10.867917,30.498162


In [ ]:
df3 - df2

,R&D Spend,Administration,Marketing Spend
0,0.00,0.0,0.0
1,-0.03,0.0,0.0
2,0.00,0.0,0.0
3,0.00,0.0,0.0
4,0.00,0.0,0.0
5,0.00,0.0,0.0
6,0.00,0.0,0.0
7,0.00,0.0,0.0
8,0.00,0.0,0.0
9,0.00,0.0,0.0
